### ISSUE TITLE
Can external contributors re-generate the tests?

### ISSUE THREAD

**Issue by yeikel** [dependabot/smoke-tests#195]
I ran ` ./dependabot test -f tests/smoke-npm-group-multidir.yaml -o tests/smoke-npm-group-multidir.yaml` but that failed with various auth errors 

The following comment from the readme mentions that you do not accept contributions 

_You're welcome to use this repo to test Dependabot functionality. However, we aren't accepting contributions at this time._

But it is not necessarily true in all situations. There are tests that don't need regeneration like https://github.com/dependabot/smoke-tests/pull/59 for example

Could you please clarify who can regenerate these?

**Comment by deivid-rodriguez** [comment]
I think the "However, we aren't accepting contributions at this time." should be removed from the README, since smoke tests are a good way to back dependabot-core contributions!

**Comment by jeffwidman** [comment]
Agreed. We _are_ accepting contributions, albeit judiciously... ie, most of the time they're updates to smoke test based on how behavior in `dependabot-core` changed. We're probably slow to accept new tests, unless there's a particular need for a new test...

That said, probably simplest to remove that line altogether for now from the Readme, if it becomes a problem down the line, we can always add back in a more nuanced version later.

Either of you care to submit a PR?

**Comment by yeikel** [comment]
> Agreed. We _are_ accepting contributions, albeit judiciously... ie, most of the time they're updates to smoke test based on how behavior in `dependabot-core` changed. We're probably slow to accept new tests, unless there's a particular need for a new test...
> 
> That said, probably simplest to remove that line altogether for now from the Readme, if it becomes a problem down the line, we can always add back in a more nuanced version later.
> 
> Either of you care to submit a PR?

Would adding this help? 

> We are accepting contributions primarily for updates to smoke tests related to changes in dependabot-core, with limited acceptance of new tests unless specifically needed

I submitted https://github.com/dependabot/smoke-tests/pull/217 in the meantime

**Comment by jeffwidman** [comment]
Your revised wording would be fine, but honestly for now just removing that sentence altogether is fine too... until/unless it becomes a problem I'm not too worried about it.

**Comment by jeffwidman** [comment]
I vote we close this as resolved for now, but I'll leave it up to you @yeikel in case there's something outstanding here that I'm unaware of.
